# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_Game_Seidl_2.ui'
#
# Created: Wed Nov  9 12:58:54 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 245)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.task_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.task_label.setFont(font)
        self.task_label.setObjectName("task_label")
        self.gridLayout.addWidget(self.task_label, 0, 1, 1, 1)
        self.action_buttons = QtGui.QGridLayout()
        self.action_buttons.setObjectName("action_buttons")
        self.button_new = QtGui.QPushButton(self.centralwidget)
        self.button_new.setObjectName("button_new")
        self.action_buttons.addWidget(self.button_new, 0, 0, 1, 1)
        self.button_end = QtGui.QPushButton(self.centralwidget)
        self.button_end.setObjectName("button_end")
        self.action_buttons.addWidget(self.button_end, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.action_buttons, 2, 1, 1, 1)
        self.statistik_label = QtGui.QGridLayout()
        self.statistik_label.setObjectName("statistik_label")
        self.wrong = QtGui.QLabel(self.centralwidget)
        self.wrong.setObjectName("wrong")
        self.statistik_label.addWidget(self.wrong, 2, 0, 1, 1)
        self.correct = QtGui.QLabel(self.centralwidget)
        self.correct.setObjectName("correct")
        self.statistik_label.addWidget(self.correct, 1, 0, 1, 1)
        self.sum = QtGui.QLabel(self.centralwidget)
        self.sum.setObjectName("sum")
        self.statistik_label.addWidget(self.sum, 3, 0, 1, 1)
        self.games = QtGui.QLabel(self.centralwidget)
        self.games.setObjectName("games")
        self.statistik_label.addWidget(self.games, 4, 0, 1, 1)
        self.sum_n = QtGui.QLabel(self.centralwidget)
        self.sum_n.setText("")
        self.sum_n.setObjectName("sum_n")
        self.statistik_label.addWidget(self.sum_n, 3, 1, 1, 1)
        self.wrong_n = QtGui.QLabel(self.centralwidget)
        self.wrong_n.setText("")
        self.wrong_n.setObjectName("wrong_n")
        self.statistik_label.addWidget(self.wrong_n, 2, 1, 1, 1)
        self.open_n = QtGui.QLabel(self.centralwidget)
        self.open_n.setText("")
        self.open_n.setObjectName("open_n")
        self.statistik_label.addWidget(self.open_n, 0, 1, 1, 1)
        self.games_n = QtGui.QLabel(self.centralwidget)
        self.games_n.setText("")
        self.games_n.setObjectName("games_n")
        self.statistik_label.addWidget(self.games_n, 4, 1, 1, 1)
        self.open = QtGui.QLabel(self.centralwidget)
        self.open.setObjectName("open")
        self.statistik_label.addWidget(self.open, 0, 0, 1, 1)
        self.correct_n = QtGui.QLabel(self.centralwidget)
        self.correct_n.setText("")
        self.correct_n.setObjectName("correct_n")
        self.statistik_label.addWidget(self.correct_n, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.statistik_label, 0, 0, 3, 1)
        self.button_zahlen = QtGui.QGridLayout()
        self.button_zahlen.setObjectName("button_zahlen")
        self.button_n_12 = QtGui.QPushButton(self.centralwidget)
        self.button_n_12.setObjectName("button_n_12")
        self.button_zahlen.addWidget(self.button_n_12, 2, 1, 1, 1)
        self.button_n_4 = QtGui.QPushButton(self.centralwidget)
        self.button_n_4.setObjectName("button_n_4")
        self.button_zahlen.addWidget(self.button_n_4, 2, 2, 1, 1)
        self.button_n_8 = QtGui.QPushButton(self.centralwidget)
        self.button_n_8.setObjectName("button_n_8")
        self.button_zahlen.addWidget(self.button_n_8, 1, 0, 1, 1)
        self.button_n_14 = QtGui.QPushButton(self.centralwidget)
        self.button_n_14.setObjectName("button_n_14")
        self.button_zahlen.addWidget(self.button_n_14, 0, 3, 1, 1)
        self.button_n_5 = QtGui.QPushButton(self.centralwidget)
        self.button_n_5.setObjectName("button_n_5")
        self.button_zahlen.addWidget(self.button_n_5, 2, 3, 1, 1)
        self.button_n_7 = QtGui.QPushButton(self.centralwidget)
        self.button_n_7.setObjectName("button_n_7")
        self.button_zahlen.addWidget(self.button_n_7, 2, 4, 1, 1)
        self.button_n_9 = QtGui.QPushButton(self.centralwidget)
        self.button_n_9.setObjectName("button_n_9")
        self.button_zahlen.addWidget(self.button_n_9, 2, 0, 1, 1)
        self.button_n_6 = QtGui.QPushButton(self.centralwidget)
        self.button_n_6.setObjectName("button_n_6")
        self.button_zahlen.addWidget(self.button_n_6, 1, 4, 1, 1)
        self.button_n_10 = QtGui.QPushButton(self.centralwidget)
        self.button_n_10.setObjectName("button_n_10")
        self.button_zahlen.addWidget(self.button_n_10, 0, 1, 1, 1)
        self.button_n_3 = QtGui.QPushButton(self.centralwidget)
        self.button_n_3.setObjectName("button_n_3")
        self.button_zahlen.addWidget(self.button_n_3, 1, 3, 1, 1)
        self.button_n_2 = QtGui.QPushButton(self.centralwidget)
        self.button_n_2.setObjectName("button_n_2")
        self.button_zahlen.addWidget(self.button_n_2, 1, 2, 1, 1)
        self.button_n_11 = QtGui.QPushButton(self.centralwidget)
        self.button_n_11.setObjectName("button_n_11")
        self.button_zahlen.addWidget(self.button_n_11, 1, 1, 1, 1)
        self.button_n_1 = QtGui.QPushButton(self.centralwidget)
        self.button_n_1.setObjectName("button_n_1")
        self.button_zahlen.addWidget(self.button_n_1, 0, 0, 1, 1)
        self.button_n_15 = QtGui.QPushButton(self.centralwidget)
        self.button_n_15.setObjectName("button_n_15")
        self.button_zahlen.addWidget(self.button_n_15, 0, 4, 1, 1)
        self.button_n_13 = QtGui.QPushButton(self.centralwidget)
        self.button_n_13.setObjectName("button_n_13")
        self.button_zahlen.addWidget(self.button_n_13, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.button_zahlen, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.button_end, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.button_new, QtCore.SIGNAL("clicked()"), MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.task_label.setText(QtGui.QApplication.translate("MainWindow", "Drücken Sie die Buttons in aufsteigender Richtung!", None, QtGui.QApplication.UnicodeUTF8))
        self.button_new.setText(QtGui.QApplication.translate("MainWindow", "Neu", None, QtGui.QApplication.UnicodeUTF8))
        self.button_end.setText(QtGui.QApplication.translate("MainWindow", "Ende", None, QtGui.QApplication.UnicodeUTF8))
        self.wrong.setText(QtGui.QApplication.translate("MainWindow", "falsch:", None, QtGui.QApplication.UnicodeUTF8))
        self.correct.setText(QtGui.QApplication.translate("MainWindow", "korrekt: ", None, QtGui.QApplication.UnicodeUTF8))
        self.sum.setText(QtGui.QApplication.translate("MainWindow", "gesamt", None, QtGui.QApplication.UnicodeUTF8))
        self.games.setText(QtGui.QApplication.translate("MainWindow", "Spiele", None, QtGui.QApplication.UnicodeUTF8))
        self.open.setText(QtGui.QApplication.translate("MainWindow", "offen:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_12.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_4.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_8.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_14.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_5.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_7.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_9.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_6.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_10.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_3.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_2.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_11.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_1.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_15.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.button_n_13.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))

